### ISSUE TITLE
Declare the license for this repository

### ISSUE THREAD

**Issue by tylere** [saveriofrancini/bap#2]
See:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by saveriofrancini** [comment]
Done, thanks
https://github.com/saveriofrancini/bap/blob/master/LICENSE.md
Saverio

Il giorno lun 10 ott 2022 alle ore 21:16 Tyler Erickson <
***@***.***> ha scritto:
